sonar.projectKey=Noah669_Chaos-Pizza-API-dassacn-rastemax
sonar.projectName=Chaos-Pizza-API
sonar.projectVersion=1.1.0
sonar.organization=noahceae
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**, data/**
