sonar.projectKey=Chaos-Pizza-API
sonar.projectName=Chaos-Pizza-API
sonar.projectVersion=1.1.0
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**, data/**